package Learn::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Learn::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=dbtodo',
        user => 'postgres',
        password => 'eokoebrz',
        AutoCommit => q{1},
    }
);

=head1 NAME

Learn::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Learn>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Learn::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Jordan Eokoe

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
